name: flutter_key_lints
description: "A Flutter custom lint package to enforce proper widget key usage for improved performance, state management, and widget tree reconciliation."
version: 1.0.1
repository: https://github.com/jmadler/flutter_key_lints
issue_tracker: https://github.com/jmadler/flutter_key_lints/issues
homepage: https://github.com/jmadler/flutter_key_lints
keywords: [flutter, lint, custom_lint, keys, performance, widgets, analyzer]

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  analyzer: "^7.3.0"
  custom_lint_builder: "^0.7.5"
  custom_lint_core: "^0.7.5"
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  custom_lint: "^0.7.5"
  mockito: ^5.4.5

# This package is a custom_lint plugin
custom_lint:
  # The resolver needs to point directly to the function that creates the plugin
  plugin: lib/flutter_key_lints.dart

flutter:
